import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { generate, schemaEntity } from './generate-listing-seo-pages.mjs';
import { generateSitemap } from './generate-sitemap.mjs';
import { ORIGIN, parseCsv, crawlAllowed, httpUrl, jsonLd } from './lib/seo.mjs';

test('CSV parser preserves quoted descriptions, commas, multiline text and escaped quotes', () => {
  assert.deepEqual(parseCsv('\uFEFFid,description\r\n1,"A, B\nHe said ""yes"""\r\n'), [{ id: '1', description: 'A, B\nHe said "yes"' }]);
});
test('photo crawl exceptions use longest matching robots rules', () => {
  const robots = 'User-agent: *\nAllow: /\nDisallow: /data/\nAllow: /data/*-images/\nDisallow: /*.csv$';
  assert.equal(crawlAllowed('/data/oxglow-listing-images/photo.jpg', robots), true);
  assert.equal(crawlAllowed('/data/pigiame-clean-images/photo.png', robots), true);
  assert.equal(crawlAllowed('/data/scraped-listings.csv', robots), false);
  assert.equal(crawlAllowed('/data/seo-page-state.json', robots), false);
  assert.equal(crawlAllowed('/index.html', robots), true);
});
test('untrusted input cannot add JSON-LD script tags or unsafe external URLs', () => {
  assert.equal(httpUrl('javascript:alert(1)'), '');
  assert.equal(httpUrl('https://user:pass@example.com/'), '');
  assert.ok(!jsonLd({ name: '</script><script>alert(1)</script>' }).includes('<'));
});
test('Product offers never invent stock, condition, or a price; services use Service', () => {
  const listing = { categoryKey: 'electronics', url: `${ORIGIN}/listing/test/`, title: 'Laptop', description: 'A laptop', imageUrls: [], details: [], currency: 'CAD', priceValue: null };
  assert.equal(schemaEntity(listing).offers, undefined);
  assert.equal(schemaEntity(listing).itemCondition, undefined);
  const offer = schemaEntity({ ...listing, priceValue: 25, source_availability: 'unknown' }).offers;
  assert.equal(offer.price, 25); assert.equal(offer.availability, undefined); assert.equal(offer.itemCondition, undefined);
  assert.equal(schemaEntity({ ...listing, categoryKey: 'services', priceValue: 25 })['@type'], 'Service');
  assert.equal(schemaEntity({ ...listing, categoryKey: 'jobs' })['@type'], 'Thing');
});
test('inventory builds paginate, deduplicate, preserve URLs, retire sold pages, and retain lastmod', async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), '6ixo-seo-'));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  await fs.mkdir(path.join(root, 'data'), { recursive: true });
  await fs.writeFile(path.join(root, 'robots.txt'), 'User-agent: *\nAllow: /');
  const home = '<!DOCTYPE html><html lang="en"><head><link rel="canonical" href="https://6ixo.com/"><meta name="robots" content="index, follow"></head><body><a href="/listings/">Listings</a></body></html>';
  await fs.writeFile(path.join(root, 'index.html'), home);
  await fs.writeFile(path.join(root, 'sitemap.xml'), '<urlset><url><loc>https://6ixo.com/</loc><lastmod>2026-09-01</lastmod></url></urlset>');
  const headers = ['id', 'status', 'app_category', 'app_subcategory', 'title', 'description', 'image_urls', 'city', 'country', 'source_url', 'price_value', 'price_text', 'currency', 'source_availability', 'scraped_at'];
  const rows = Array.from({ length: 40 }, (_, i) => ({ id: `id-${i}`, status: 'published', app_category: 'electronics', title: `Laptop ${i}`, description: 'A complete description of this laptop and its useful features.', image_urls: 'https://example.com/photo.jpg', city: 'Toronto', country: 'Canada', source_url: `https://example.com/ad/${i}`, price_value: '2500', price_text: '$25', currency: 'CAD', source_availability: 'unknown', scraped_at: '2026-10-01' }));
  const writeFeed = async records => fs.writeFile(path.join(root, 'data/scraped-listings.csv'), headers.join(',') + '\n' + records.map(row => headers.map(h => `"${String(row[h] || '').replaceAll('"', '""')}"`).join(',')).join('\n'));
  await writeFeed([...rows, rows[0], { ...rows[1], id: 'duplicate-source' }, { ...rows[0], id: 'rejected', status: 'rejected' }, { ...rows[0], id: 'sold', source_availability: 'sold' }]);
  const first = await generate(root);
  assert.equal(first.count, 40);
  assert.ok(first.indexes.some(i => i.url === `${ORIGIN}/listings/page/2/`));
  const firstPage = await fs.readFile(path.join(root, 'listings/index.html'), 'utf8');
  assert.equal([...firstPage.matchAll(/class="listing-index-card"/g)].length, 36);
  assert.ok(firstPage.includes('href="/listings/page/2/"'));
  const firstListing = first.listings.find(l => l.id === 'id-0');
  const listingFile = path.join(root, 'listing', firstListing.slug, 'index.html');
  const listingHtml = await fs.readFile(listingFile, 'utf8');
  assert.ok(listingHtml.includes('"price":25'));
  assert.ok(!listingHtml.includes('InStock'));
  const firstState = await generateSitemap(root, new Date('2026-10-08T16:00:00Z'));
  const sitemapBefore = await fs.readFile(path.join(root, 'sitemap.xml'), 'utf8');
  const statBefore = await fs.stat(listingFile);
  await generate(root);
  await generateSitemap(root, new Date('2026-10-09T16:00:00Z'));
  assert.equal(await fs.readFile(path.join(root, 'sitemap.xml'), 'utf8'), sitemapBefore);
  assert.equal((await fs.stat(listingFile)).mtimeMs, statBefore.mtimeMs);
  assert.ok(sitemapBefore.includes('<image:loc>https://example.com/photo.jpg</image:loc>'));
  rows[0].title = 'A renamed laptop'; rows[1].source_availability = 'sold';
  await writeFeed(rows);
  const next = await generate(root);
  assert.equal(next.count, 39);
  assert.equal(next.listings.find(l => l.id === 'id-0').slug, firstListing.slug);
  assert.ok(next.retired.some(l => l.id === 'id-1'));
  const retiredFile = path.join(root, 'listing', first.listings.find(l => l.id === 'id-1').slug, 'index.html');
  assert.ok((await fs.readFile(retiredFile, 'utf8')).includes('noindex, follow'));
  const state = await generateSitemap(root, new Date('2026-10-09T16:00:00Z'));
  assert.equal(state[firstListing.url].lastmod, '2026-10-09');
  assert.equal(state[first.listings.find(l => l.id === 'id-1').url], undefined);
  assert.equal(state[`${ORIGIN}/`].lastmod, firstState[`${ORIGIN}/`].lastmod);
  await writeFeed([]);
  await assert.rejects(generate(root), /Refusing to retire every listing/);
});
