create table if not exists public.promotion_payments (
    id bigint generated by default as identity primary key,
    stripe_event_id text not null unique,
    stripe_event_type text not null,
    stripe_event_created_at timestamptz,
    stripe_session_id text,
    stripe_payment_intent_id text,
    stripe_customer_id text,
    stripe_customer_email text,
    placement text,
    app text,
    payment_method text,
    amount_total_cents bigint,
    currency text,
    status text,
    payment_status text,
    raw_event jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists promotion_payments_event_created_idx
    on public.promotion_payments (stripe_event_created_at desc);

create index if not exists promotion_payments_session_idx
    on public.promotion_payments (stripe_session_id);

create index if not exists promotion_payments_payment_intent_idx
    on public.promotion_payments (stripe_payment_intent_id);

create index if not exists promotion_payments_created_idx
    on public.promotion_payments (created_at desc);

alter table public.promotion_payments enable row level security;
