create table if not exists public.app_client_state (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    state_key text not null,
    state_value jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint app_client_state_user_key_unique unique (user_id, state_key)
);

create index if not exists app_client_state_user_idx
    on public.app_client_state (user_id);

create index if not exists app_client_state_updated_idx
    on public.app_client_state (updated_at desc);

alter table public.app_client_state enable row level security;

drop policy if exists "app_client_state_select_own" on public.app_client_state;
create policy "app_client_state_select_own"
    on public.app_client_state
    for select
    to authenticated
    using (auth.uid() = user_id);

drop policy if exists "app_client_state_insert_own" on public.app_client_state;
create policy "app_client_state_insert_own"
    on public.app_client_state
    for insert
    to authenticated
    with check (auth.uid() = user_id);

drop policy if exists "app_client_state_update_own" on public.app_client_state;
create policy "app_client_state_update_own"
    on public.app_client_state
    for update
    to authenticated
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "app_client_state_delete_own" on public.app_client_state;
create policy "app_client_state_delete_own"
    on public.app_client_state
    for delete
    to authenticated
    using (auth.uid() = user_id);
