create table if not exists public.promo_codes (
    id bigint generated by default as identity primary key,
    code text not null unique,
    active boolean not null default true,
    discount_type text not null check (discount_type in ('percent', 'fixed')),
    discount_value numeric(10, 2) not null check (discount_value > 0),
    currency text,
    starts_at timestamptz,
    ends_at timestamptz,
    max_redemptions integer,
    per_customer_limit integer,
    placement_scope text[],
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists promo_codes_active_idx
    on public.promo_codes (active, starts_at, ends_at);

create table if not exists public.promo_redemptions (
    id bigint generated by default as identity primary key,
    promo_code_id bigint references public.promo_codes(id) on delete set null,
    promo_code text not null,
    customer_ref text,
    stripe_event_id text unique,
    stripe_payment_intent_id text,
    stripe_session_id text,
    amount_before_cents bigint,
    discount_cents bigint,
    amount_after_cents bigint,
    currency text,
    placement text,
    status text not null default 'succeeded',
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists promo_redemptions_code_idx
    on public.promo_redemptions (promo_code);

create index if not exists promo_redemptions_customer_idx
    on public.promo_redemptions (customer_ref);

create index if not exists promo_redemptions_created_idx
    on public.promo_redemptions (created_at desc);

alter table public.promo_codes enable row level security;
alter table public.promo_redemptions enable row level security;

insert into public.promo_codes (
    code,
    active,
    discount_type,
    discount_value,
    currency,
    max_redemptions,
    per_customer_limit,
    placement_scope
)
values (
    'DEMO10',
    true,
    'percent',
    10,
    'USD',
    100000,
    1000,
    null
)
on conflict (code) do nothing;
